[package]
name = "aliba/robloxdevstack"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Promise = "evaera/promise@4.0.0"
Roact = "roblox/roact@1.4.4"
Signal = "sleitnick/signal@2.0.3"
Fusion = "elttob/fusion@0.3.0"

[dev-dependencies]
TestEZ = "roblox/testez@0.4.1"
